import type { Metadata } from "next";
import { Onest } from "next/font/google"
import "./globals.css";
import { MenuMobile } from "./_components/menu-mobile";
import { Sidebar } from "./_components/sidebar";
import { TopBar } from "@/components/topbar";
import { Footer } from "@/components/footer";

const fontsans = Onest({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Edunex",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${fontsans.className} antialiased bg-primary-50`}
      >
        <div className="h-full w-full">
        <aside className="fixed hidden md:block bg-white h-screen w-full max-w-[256px] z-30">
          <Sidebar />
        </aside>

        <main className="flex-1 h-full py-[30px] md:py-7 md:mt-0 md:ml-[256px]">
          <section className="w-full flex flex-col gap-4 md:gap-7 px-4 md:px-7 h-full mx-auto max-w-7xl">
            <div className="hidden md:block">
             <TopBar/>
            </div>
            {children}
          </section>
          <footer className="mt-16">
          <Footer />
        </footer>
        </main>

        <div className="md:hidden fixed z-50 bottom-0 left-0 w-full">
          <MenuMobile />
        </div>
        
        </div>
      </body>
    </html>
  );
}
